apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myhttpddeploy
  name: myhttpddeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myhttpddeploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myhttpddeploy
    spec:
      containers:
      - image: registry.access.redhat.com/ubi9/httpd-24
        name: httpd-24
        volumeMounts:
          - mountPath: /var/www/html/
            name: www
        ports:
        - containerPort: 8080
        resources: {}
      volumes:
        - name: www
          persistentVolumeClaim:
            claimName: www-pvc
status: {}

